//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTruyenHay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachDocTruyen
    {
        public string DanhSachDocTruyenid { get; set; }
        public string DanhSachDocID { get; set; }
        public string TruyenID { get; set; }
        public Nullable<System.DateTime> NgayThem { get; set; }
    
        public virtual DanhSachDoc DanhSachDoc { get; set; }
        public virtual Truyen Truyen { get; set; }
    }
}
