//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTruyenHay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        public int IDDanhGia { get; set; }
        public string NguoiDungID { get; set; }
        public string TruyenID { get; set; }
        public Nullable<int> DiemDanhGia { get; set; }
        public string NhanXet { get; set; }
        public Nullable<System.DateTime> NgayDanhGia { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual Truyen Truyen { get; set; }
    }
}
