//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTruyenHay.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Truyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Truyen()
        {
            this.Chuongs = new HashSet<Chuong>();
            this.DanhGias = new HashSet<DanhGia>();
            this.DanhSachDocTruyens = new HashSet<DanhSachDocTruyen>();
            this.ThongBaos = new HashSet<ThongBao>();
            this.TienDoDocs = new HashSet<TienDoDoc>();
            this.TruyenDanhMucs = new HashSet<TruyenDanhMuc>();
        }
        public HttpPostedFileBase UploadImage { get; set; }
        public string IDtruyen { get; set; }
        public string TieuDe { get; set; }
        public string MoTa { get; set; }
        public string TacGia { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string TrangThai { get; set; }
        public string imagetruyen { get; set; }
        public string theloai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chuong> Chuongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhSachDocTruyen> DanhSachDocTruyens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongBao> ThongBaos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TienDoDoc> TienDoDocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TruyenDanhMuc> TruyenDanhMucs { get; set; }
    }
}
