//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTruyenHay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruyenDanhMuc
    {
        public string IDTruyenDanhMuc { get; set; }
        public string TruyenID { get; set; }
        public string DanhMucID { get; set; }
    
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual Truyen Truyen { get; set; }
    }
}
